---
- name: Download MySQL package
  get_url:
    url: "{{ mysql_pkg_url }}"
    dest: "{{ mysql_pkg_path }}"

- name: Install MySQL
  command: "{{ mysql_pkg_installer_cmd }}"
  become: yes

- name: Start MySQL
  command: "{{ mysql_server_script }} start"
  become: yes

- name: Wait for MySQL
  wait_for:
    port: "{{ mysql_port }}"
    timeout: 60
